mytube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls', namespace='service')),
]

urlpatterns += staticfiles_urlpatterns()

service/urls.py
from django.urls import path
from service.views import IndexView, FolderDetailView, SubfolderCreateView


app_name = 'service'

urlpatterns = [
    path("", IndexView.as_view(), name='index'),
    path("folder/<int:folder_id>/", FolderDetailView.as_view(), name='folder_view'),
    path("folder/<int:folder_id>/create-subfolder/", SubfolderCreateView.as_view(), name='subfolder_create'),
]

service/models.py
from django.db import models
from embed_video.fields import EmbedVideoField


class Folder(models.Model):
    name = models.CharField(max_length=100, unique=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='subfolders', null=True, blank=True)
    is_public = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self) -> str:
        return f"{self.name}"
    
    def get_full_path(self):
        paths = []
        folder = self
        while folder:
            paths.append(folder)
            folder = folder.parent
        return reversed(paths)
    

class Video(models.Model):
    name = models.CharField(max_length=255, unique=True)
    desc = models.CharField(max_length=255, null=True)
    url = EmbedVideoField()
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE, related_name='videos')
    added_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self) -> str:
        return f"{self.folder.name}/{self.name}"
    
    
    

    
    

service/forms.py
from django import forms

from service.models import Folder, Video


class FolderForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = ['name', 'parent', 'is_public']
        

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        exclude = ['added_at', 'modified_at']

service/views.py
from django.shortcuts import render, redirect
from django import views

from service.models import Folder, Video
from service.forms import FolderForm, VideoForm

class IndexView(views.View):
    form_class = FolderForm
    template_name = "index.html"
    
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        folders = Folder.objects.filter(parent=None)
        context = {
            "folders": folders,
            "form": form
        }
        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        
        form = self.form_class(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect('service:index')
        
        folders = Folder.objects.filter(parent=None)
        context = {
            "folders": folders,
            "form": form,
            "errors": form.errors,
        }
        return render(request, self.template_name, context)
        

class FolderDetailView(views.View):
    
    def get(self, request, folder_id, *args, **kwargs):
        folder = Folder.objects.get(pk=folder_id)
        videos = folder.videos.all()
        subfolders = folder.subfolders.all()
        form = FolderForm(initial={'parent':folder})
        breadcrumbs = folder.get_full_path()
        context = {
            "folder": folder,
            "subfolders": subfolders,
            "videos": videos,
            "form": form,
            "breadcrumbs": breadcrumbs
        }
        return render(request, template_name='folder_view.html', context=context)
    
    def post(self, request, folder_id, *args, **kwargs):
        folder = Folder.objects.get(pk=folder_id)
        if folder.parent is None:
            folder.delete()
            return redirect("service:index")
        folder.delete()
        return redirect("service:folder_view",folder_id=folder.parent.id)
    

class SubfolderCreateView(views.View):
    form_class = FolderForm

    def post(self, request, folder_id, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect("service:folder_view", folder_id=folder_id)
        
        return redirect("service:folder_view", folder_id=folder_id)
        
        
        
        
        
    
# Todo: Add and remove folder functionality

service/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    </head>
    <body>
        <h1> Welcome to MyTube </h1>

        {% block content %}

        {% endblock %}
        
        <script src="" async defer></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    </body>
</html>

service/templates/folder_view.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% block content %}


<div class="container-fluid parent-container">
    <div class="row">
        <!-- Breadcrumbs to show folder hierarchy -->
        <div class="col-11  mb-3">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    {% for item in breadcrumbs %}
                        <li class="breadcrumb-item {% if forloop.last %}active{% endif %}">
                            {% if forloop.last %}
                                {{ item.name }}
                            {% else %}
                                <a href="{% url 'service:folder_view' item.id %}">{{ item.name }}</a>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ol>
            </nav>
        </div>
        <!-- Delete button links to the Delete Folder Modal -->
        <div class="col-1  mb-3">
            <a href="#" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deletefoldermodal">Delete Folder</a>
        </div>

    </div>
    
    <!-- Subfolders Section -->
    <div class="subfolders-section mb-4">
        <h3>Subfolders</h3>
        <div class="row">
            {% include 'newsubfolder.html' %}

            {% for subfolder in subfolders %}
                <div class="col-6 col-md-3 col-lg-1-5 text-center">
                    <a href="{% url 'service:folder_view' subfolder.id %}" class="text-decoration-none">
                        <i class="bi bi-folder-fill" style="font-size: 3rem; color: #ffc107;"></i>
                        <p class="mt-2">{{ subfolder.name }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- Videos Section -->
    <div class="videos-section">
        <h3>Videos</h3>
        <div class="row">
            {% for video in videos %}
                <div class="col-12 col-md-3 mb-4">
                    <div class="embed-responsive embed-responsive-16by9">
                        {% video video.url '320x240' %}
                    </div>
                    <div class="mt-2">
                        <h5>{{ video.name }}</h5>
                        <p>{{ video.desc }}</p>
                        <small class="text-muted">Added on: {{ video.added_at|date:"F j, Y, g:i a" }}</small>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

<!-- Delete Folder Modal -->
<div class="modal" tabindex="-1" id="deletefoldermodal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Confirm Deleteion of Folder</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cancel"></button>
        </div>
        <div class="modal-body">
            <h3>Are you sure to delete this folder with all it's content?</h3>
            <form method="POST" action="{% url 'service:folder_view' folder.id %}">
                {% csrf_token %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-primary">Yes</button>
                </div>
            </form>
      </div>
    </div>
</div>



{% endblock %}

service/templates/index.html
{% extends "base.html" %}
{% block content %}

<div class="container-fluid parent-container">
    <h2>Your Space</h2>

    <div class="subfolders-section mb-4">
        
        <div class="row">
            {% include 'newfolder.html' %}
            
            {% for folder in folders %}
                <div class="col-6 col-md-3 col-lg-1-5 text-center">
                    <a href="{% url 'service:folder_view' folder.id %}" class="text-decoration-none">
                        <i class="bi bi-folder-fill" style="font-size: 3rem; color: #ffc107;"></i>
                        <p class="mt-2">{{ folder.name }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    {% if errors %}
        <div>
            <p> {{ errors }} </p>
        </div>
    {% endif %}

</div>

{% endblock %}

service/templates/newfolder.html
<div class="col-6 col-md-3 col-lg-1-5 text-center">
    <a href="#" class="text-decoration-none" data-bs-toggle="modal" data-bs-target="#newfoldermodal">
        <i class="bi bi-folder-plus" style="font-size: 3rem; color: #ffc107;"></i>
        <p class="mt-2">New Folder</p>
    </a>
</div>

<div class="modal" tabindex="-1" id="newfoldermodal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Create New Folder</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cancel"></button>
        </div>
        <div class="modal-body">
          <form method="POST" action="{% url 'service:index' %}">
            {% csrf_token %}
            {{ form.as_p }}
          
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </form>
      </div>
    </div>
</div>

service/templates/newsubfolder.html
<div class="col-6 col-md-3 col-lg-1-5 text-center">
    <a href="#" class="text-decoration-none" data-bs-toggle="modal" data-bs-target="#newsubfoldermodal">
        <i class="bi bi-folder-plus" style="font-size: 3rem; color: #ffc107;"></i>
        <p class="mt-2">New Folder</p>
    </a>
</div>

<div class="modal" tabindex="-1" id="newsubfoldermodal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Create New Folder</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cancel"></button>
        </div>
        <div class="modal-body">
          <form method="POST" action="{% url 'service:subfolder_create' folder.id %}">
            {% csrf_token %}
            {{ form.as_p }}
          
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </form>
      </div>
    </div>
</div>